import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
// import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'

export default function Home() {
  const counter = useSelector((state)=> state.counter);
  const dispatch = useDispatch();
  const increment = () => {
    dispatch({type: 'INC'})
  }

  const decrement = () => {
    dispatch({type: 'DEC'})
  }

  const AddBy = () => {
    dispatch({type: 'ADD', payLoad: 10})
  }

  const DecBy = () => {
    dispatch({type: 'DEC10', payLoads: 10})
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Counter App</h1>
        <h2>{counter}</h2>
        <button onClick={increment}>Increment</button>
        <button onClick={decrement}>Decrement</button>
        <button onClick={AddBy}>Add By 10</button>
        <button onClick={DecBy}>Dec By 10</button>
      </div>
    </div>
  )
}
